{% set name = "pipestat" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipestat-{{ version }}.tar.gz
  sha256: 94bcf0d34f9d7cfaa21fb8b3d4872932a98186eb726062e7cf04a2c26f4f8b99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - pipestat = pipestat.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools
    - jsonschema
    - logmuse >=0.2.5
    - ubiquerg >=0.6.1
    - yacman >=0.9.3
    - pyyaml
    - pandas
    - eido
    - jinja2

test:
  imports:
    - pipestat
  commands:
    - pipestat --help

about:
  home: https://github.com/pepkit/pipestat
  summary: A pipeline results reporter
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pipestat.databio.org/en/latest/
  dev_url: https://github.com/pepkit/pipestat

extra:
  recipe-maintainers:
    - mencian
