{% set name = "pipestat" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipestat-{{ version }}.tar.gz
  sha256: 8dbb05e483663e7135a6c58faeaa8ca7a7ed95532202abfc240cc9324d9bfd9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pipestat = pipestat.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools
    - jsonschema
    - logmuse >=0.2.5
    - oyaml
    - psycopg2
    - pydantic >=1.10.7,<2.0.0
    - sqlmodel >=0.0.8
    - ubiquerg >=0.6.1
    - yacman >=0.9.1
    - pyyaml
    - pandas
    - eido
    - jinja2

test:
  imports:
    - pipestat
  commands:
    - pipestat --help

about:
  home: https://github.com/pepkit/pipestat
  summary: A pipeline results reporter
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pipestat.databio.org/en/latest/
  dev_url: https://github.com/pepkit/pipestat

extra:
  recipe-maintainers:
    - mencian
